---
name: 'Build and Publish nezha-dashboard'

on:
  push:
    tags:
      - 'v*'
  schedule:
    - cron: '0 16 1 * *'
  workflow_dispatch:

permissions:
  actions: write
  contents: read

defaults:
  run:
    shell: bash -ex {0}

env:
  IPINFO_TOKEN: ${{ secrets.IPINFO_TOKEN }}
  DOCKER_USERNAME: ${{ github.repository_owner }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build_v0:
    name: 'Build and Publish nezha-dashboard ${{ matrix.NEZHA_VERSION }}'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        NEZHA_VERSION: [ 'v0.18.6', 'v0.20.13' ]

    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: 'Download geoip db file'
        run: |
          cd ${{ github.workspace }}/v0
          wget --tries=50 -qO geoip.db https://ipinfo.io/data/free/country.mmdb?token=${IPINFO_TOKEN}

      - name: 'Set up Docker QEMU'
        uses: docker/setup-qemu-action@v3

      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v3

      - name: 'Login to DockerHub'
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: 'Extract Docker metadata'
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_USERNAME }}/nezha-dashboard
          tags: type=raw,value=${{ matrix.NEZHA_VERSION }}

      - name: 'Build and Push nezha-dashboard image'
        uses: docker/build-push-action@v6
        with:
          context: ${{ github.workspace }}/v0
          file: ${{ github.workspace }}/v0/Dockerfile
          platforms: linux/amd64, linux/arm64/v8
          build-args: NEZHA_VERSION=${{ matrix.NEZHA_VERSION }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true

  build_v1:
    name: 'Build and Publish nezha-dashboard v1'
    runs-on: ubuntu-latest

    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: 'Fetch Versions and Determine Build'
        id: bump_version
        run: |
          NEZHA_VERSION="$(wget -qO- --tries=50 --header="Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/nezhahq/nezha/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')"
          echo "version=${NEZHA_VERSION}" >> $GITHUB_OUTPUT

      - name: 'Download geoip db file'
        run: |
          cd ${{ github.workspace }}/v1
          wget --tries=50 -qO geoip.db https://ipinfo.io/data/free/country.mmdb?token=${IPINFO_TOKEN}

      - name: 'Set up Docker QEMU'
        uses: docker/setup-qemu-action@v3

      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v3

      - name: 'Login to DockerHub'
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: 'Extract Docker metadata'
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_USERNAME }}/nezha-dashboard
          tags: |
            type=raw,value=${{ steps.bump_version.outputs.version }}
            type=raw,value=latest

      - name: 'Build and Push nezha-dashboard image'
        uses: docker/build-push-action@v6
        with:
          context: ${{ github.workspace }}/v1
          file: ${{ github.workspace }}/v1/Dockerfile
          platforms: linux/amd64, linux/arm64/v8
          build-args: NEZHA_VERSION=${{ steps.bump_version.outputs.version }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true

  cleaning_workflow:
    name: 'Cleaning up old workflows'
    needs:
      - build_v0
      - build_v1
    runs-on: ubuntu-latest

    steps:
      - name: 'Cleaning up old workflows'
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
          delete_run_by_conclusion_pattern: "cancelled, skipped, success"